version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - ./:/usr/src/app:delegated
      # If you want node to pick live edits you can run with nodemon locally (not in this container)
    environment:
      - NODE_ENV=development
      - PUPPETEER_EXECUTABLE_PATH=${PUPPETEER_EXECUTABLE_PATH:-}
    stdin_open: true
    tty: true
